from fpdf import FPDF
import os

def generate_pdf_report(patient_name, image_path, prediction, confidence, extra_info=""):
    """
    Generate PDF report with patient info, prediction, and optional extra fields.
    
    Args:
        patient_name (str): Patient's full name.
        image_path (str): Path to the MRI image.
        prediction (str): Predicted tumor class.
        confidence (float): Confidence score.
        extra_info (str or list): Can be a string (legacy) or a list of dicts with keys: label, value, type, path.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt="Brain Tumor MRI Report", ln=1, align="C")
    pdf.ln(10)
    
    # Patient Information (basic)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, txt="Patient Information", ln=1)
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 8, txt=f"Name: {patient_name}", ln=1)
    
    # If extra_info is a string (legacy), treat as basic info lines
    if isinstance(extra_info, str):
        for line in extra_info.split("\n"):
            if line.strip():
                pdf.cell(200, 8, txt=line, ln=1)
    else:
        # New format: list of dicts
        for field in extra_info:
            label = field.get("label", "")
            value = field.get("value", "")
            ftype = field.get("type", "text")
            if ftype == "image" and field.get("path") and os.path.exists(field["path"]):
                pdf.cell(200, 8, txt=f"{label}:", ln=1)
                pdf.image(field["path"], x=10, y=pdf.get_y(), w=50)
                pdf.ln(40)
            else:
                pdf.cell(200, 8, txt=f"{label}: {value}", ln=1)
    pdf.ln(5)
    
    # Diagnosis
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, txt="Diagnosis Result", ln=1)
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 8, txt=f"Prediction: {prediction}", ln=1)
    pdf.cell(200, 8, txt=f"Confidence: {confidence:.2%}", ln=1)
    pdf.ln(5)
    
    # MRI Image
    pdf.set_font("Arial", "B", 12)
    pdf.cell(200, 10, txt="MRI Image", ln=1)
    if os.path.exists(image_path):
        pdf.image(image_path, x=10, y=pdf.get_y(), w=100)
    
    # Footer
    pdf.set_y(-20)
    pdf.set_font("Arial", "I", 8)
    pdf.cell(0, 10, txt="Generated by Brain Tumor ViT System", align="C")
    
    return pdf.output(dest='S').encode('latin-1')